services:
  pgscv-waitlist:
    image: pgscv-daf:latest
    container_name: pgscv-waitlist
    restart: unless-stopped
    volumes:
      - ./../config/pgscv-waitlist.yaml:/etc/pgscv.yaml:ro
      - ./../secrets/waitlist.conn:/run/secrets/waitlist.conn:ro
      - /home/daf/.ssh/id_ed25519_pgcli:/run/secrets/ssh_key:ro
    command: ["--config-file=/etc/pgscv.yaml"]
    network_mode: host
